auth_token: |
    "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2NmFjOTk3ZC0wNzFlLTQ1N2QtOTY0NC0zYjNhYmYwZmFiZTgifQ.eyJleHAiOjE3MDA1MDAxNjAsImlhdCI6MTcwMDQ5ODM2MCwianRpIjoiZGIwMWE4MmYtODc4My00ZGYyLWI1MzQtM2NjMmVmOGRmMDZlIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5kZXYuaWNvcy45MS4xMDkuNTYuMjE0LnNzbGlwLmlvL3JlYWxtcy9pY29zLWRldiIsImF1ZCI6Imh0dHBzOi8va2V5Y2xvYWsuZGV2Lmljb3MuOTEuMTA5LjU2LjIxNC5zc2xpcC5pby9yZWFsbXMvaWNvcy1kZXYiLCJzdWIiOiJkZTIzYTUzYy00MTIzLTQ3Y2YtYjBhZi04ZGQzY2M0YTVmMTEiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoic2hlbGwtYmFja2VuZCIsInNlc3Npb25fc3RhdGUiOiJhNDExMjBjNy00YzdkLTQ0MTEtYjEwYi1kZTcwOGNiYmExNjkiLCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiYTQxMTIwYzctNGM3ZC00NDExLWIxMGItZGU3MDhjYmJhMTY5In0.ah5CYigZvs_Bx-8SdUgKp0jcutyVqHoPW3Org5dhk4Q"
controller: localhost:8080
keycloak:
    pass: Iki946D56!!J@gSHpuonoUyH1uB*^i
    user: admin
lighthouse: lighthouse.icos-project.eu:8080
