auth_token: |
    "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2NmFjOTk3ZC0wNzFlLTQ1N2QtOTY0NC0zYjNhYmYwZmFiZTgifQ.eyJleHAiOjE3MDA3NDkyNDEsImlhdCI6MTcwMDc0NzQ0MSwianRpIjoiYWZkNWZiNDktM2U4MC00ZDc4LTk3ZDEtZDc3Y2M2NjYyNWNjIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5kZXYuaWNvcy45MS4xMDkuNTYuMjE0LnNzbGlwLmlvL3JlYWxtcy9pY29zLWRldiIsImF1ZCI6Imh0dHBzOi8va2V5Y2xvYWsuZGV2Lmljb3MuOTEuMTA5LjU2LjIxNC5zc2xpcC5pby9yZWFsbXMvaWNvcy1kZXYiLCJzdWIiOiJkZTIzYTUzYy00MTIzLTQ3Y2YtYjBhZi04ZGQzY2M0YTVmMTEiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoic2hlbGwtYmFja2VuZCIsInNlc3Npb25fc3RhdGUiOiI2YjZjZjIyMi1mMGU4LTQxZGEtYjY0OS1kOTFiZWJhNTYyMWQiLCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiNmI2Y2YyMjItZjBlOC00MWRhLWI2NDktZDkxYmViYTU2MjFkIn0.Xj8iNI9k-U-cjqzFmCgDfWcAmqfFKl1DEasTVls8f_M"
controller: localhost:8080
keycloak:
    pass: Iki946D56!!J@gSHpuonoUyH1uB*^i
    user: admin
lighthouse: lighthouse.icos-project.eu:8080
