auth_token: |
    "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2NmFjOTk3ZC0wNzFlLTQ1N2QtOTY0NC0zYjNhYmYwZmFiZTgifQ.eyJleHAiOjE3MDAxMzAyNzgsImlhdCI6MTcwMDEyODQ3OCwianRpIjoiZmZmMTMxMTItYjg1NC00NzcxLTllMTMtNDZlY2QzODIxMmQ5IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5kZXYuaWNvcy45MS4xMDkuNTYuMjE0LnNzbGlwLmlvL3JlYWxtcy9pY29zLWRldiIsImF1ZCI6Imh0dHBzOi8va2V5Y2xvYWsuZGV2Lmljb3MuOTEuMTA5LjU2LjIxNC5zc2xpcC5pby9yZWFsbXMvaWNvcy1kZXYiLCJzdWIiOiJkZTIzYTUzYy00MTIzLTQ3Y2YtYjBhZi04ZGQzY2M0YTVmMTEiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoic2hlbGwtYmFja2VuZCIsInNlc3Npb25fc3RhdGUiOiJkMDc0NzRhYS1jNGQ5LTQ2YmMtODIxNy1lYzc2N2NmNTNhYWEiLCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiZDA3NDc0YWEtYzRkOS00NmJjLTgyMTctZWM3NjdjZjUzYWFhIn0.L_u-n2jAemJysdFjIJ8gtf_CsCVulWhzzxsskCCEN7A"
controller: 10.160.3.20:31782
keycloak:
    pass: Iki946D56!!J@gSHpuonoUyH1uB*^i
    user: admin
lighthouse: lighthouse.icos-project.eu:8080
