auth_token: |
    "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2NmFjOTk3ZC0wNzFlLTQ1N2QtOTY0NC0zYjNhYmYwZmFiZTgifQ.eyJleHAiOjE3MDA3NTY4ODMsImlhdCI6MTcwMDc1NTA4MywianRpIjoiZjU2Y2Y4MjEtYzE4Ny00ZDk2LWI2ZDQtMzhhNGY5Y2ZhNWUwIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5kZXYuaWNvcy45MS4xMDkuNTYuMjE0LnNzbGlwLmlvL3JlYWxtcy9pY29zLWRldiIsImF1ZCI6Imh0dHBzOi8va2V5Y2xvYWsuZGV2Lmljb3MuOTEuMTA5LjU2LjIxNC5zc2xpcC5pby9yZWFsbXMvaWNvcy1kZXYiLCJzdWIiOiJkZTIzYTUzYy00MTIzLTQ3Y2YtYjBhZi04ZGQzY2M0YTVmMTEiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoic2hlbGwtYmFja2VuZCIsInNlc3Npb25fc3RhdGUiOiJjNzAwMGNjMy0xNDRmLTRhNzUtYjI0Mi05Yzg3M2UxYWQ2ZjYiLCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiYzcwMDBjYzMtMTQ0Zi00YTc1LWIyNDItOWM4NzNlMWFkNmY2In0.Gz0i2kbQGAJ8hRy1yewY-Ew2hf4kKbQgCQtF1bKDzuA"
controller: localhost:8080
keycloak:
    pass: Iki946D56!!J@gSHpuonoUyH1uB*^i
    user: admin
lighthouse: lighthouse.icos-project.eu:8080
