auth_token: |
    "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2NmFjOTk3ZC0wNzFlLTQ1N2QtOTY0NC0zYjNhYmYwZmFiZTgifQ.eyJleHAiOjE3MDAyMzMxNjgsImlhdCI6MTcwMDIzMTM2OCwianRpIjoiMjE1M2IzN2ItYzNkNi00YzhmLTk0MmQtYzM3NDgyMTdkZDY0IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5kZXYuaWNvcy45MS4xMDkuNTYuMjE0LnNzbGlwLmlvL3JlYWxtcy9pY29zLWRldiIsImF1ZCI6Imh0dHBzOi8va2V5Y2xvYWsuZGV2Lmljb3MuOTEuMTA5LjU2LjIxNC5zc2xpcC5pby9yZWFsbXMvaWNvcy1kZXYiLCJzdWIiOiJkZTIzYTUzYy00MTIzLTQ3Y2YtYjBhZi04ZGQzY2M0YTVmMTEiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoic2hlbGwtYmFja2VuZCIsInNlc3Npb25fc3RhdGUiOiI1NmYxNzEzZS1mMzk1LTRhOGYtOTExOS02YTc0NDk0ZGYxOTQiLCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiNTZmMTcxM2UtZjM5NS00YThmLTkxMTktNmE3NDQ5NGRmMTk0In0.J7azraS4kvRGV3TFk9LAXoaPd9WlOgJHBLemqUv4eSU"
controller: 10.160.3.20:30500
keycloak:
    pass: Iki946D56!!J@gSHpuonoUyH1uB*^i
    user: admin
lighthouse: lighthouse.icos-project.eu:8080
