/*
 * ICOS Shell
 *
 * This is the ICOS Shell based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package shellbackend

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// DeploymentApiController binds http requests to an api service and writes the service results to the http response
type DeploymentApiController struct {
	service DeploymentApiServicer
	errorHandler ErrorHandler
}

// DeploymentApiOption for how the controller is set up.
type DeploymentApiOption func(*DeploymentApiController)

// WithDeploymentApiErrorHandler inject ErrorHandler into controller
func WithDeploymentApiErrorHandler(h ErrorHandler) DeploymentApiOption {
	return func(c *DeploymentApiController) {
		c.errorHandler = h
	}
}

// NewDeploymentApiController creates a default api controller
func NewDeploymentApiController(s DeploymentApiServicer, opts ...DeploymentApiOption) Router {
	controller := &DeploymentApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DeploymentApiController
func (c *DeploymentApiController) Routes() Routes {
	return Routes{ 
		{
			"CreateDeployment",
			strings.ToUpper("Post"),
			"/api/v3/deployment/",
			c.CreateDeployment,
		},
		{
			"DeleteDeploymentById",
			strings.ToUpper("Delete"),
			"/api/v3/deployment/{deploymentId}",
			c.DeleteDeploymentById,
		},
		{
			"GetDeploymentById",
			strings.ToUpper("Get"),
			"/api/v3/deployment/{deploymentId}",
			c.GetDeploymentById,
		},
		{
			"GetDeployments",
			strings.ToUpper("Get"),
			"/api/v3/deployment/",
			c.GetDeployments,
		},
		{
			"UpdateDeployment",
			strings.ToUpper("Put"),
			"/api/v3/deployment/{deploymentId}",
			c.UpdateDeployment,
		},
	}
}

// CreateDeployment - Creates a new deployment
func (c *DeploymentApiController) CreateDeployment(w http.ResponseWriter, r *http.Request) {
	createDeploymentRequestParam := CreateDeploymentRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&createDeploymentRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertCreateDeploymentRequestRequired(createDeploymentRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateDeployment(r.Context(), createDeploymentRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// DeleteDeploymentById - Deletes a deployment
func (c *DeploymentApiController) DeleteDeploymentById(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	deploymentIdParam, err := parseInt64Parameter(params["deploymentId"], true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.DeleteDeploymentById(r.Context(), deploymentIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetDeploymentById - Find deployment by ID
func (c *DeploymentApiController) GetDeploymentById(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	deploymentIdParam, err := parseInt64Parameter(params["deploymentId"], true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.GetDeploymentById(r.Context(), deploymentIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetDeployments - Returns a list of deployments
func (c *DeploymentApiController) GetDeployments(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetDeployments(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// UpdateDeployment - Updates a deployment
func (c *DeploymentApiController) UpdateDeployment(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	deploymentIdParam, err := parseInt64Parameter(params["deploymentId"], true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	createDeploymentRequestParam := CreateDeploymentRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&createDeploymentRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertCreateDeploymentRequestRequired(createDeploymentRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateDeployment(r.Context(), deploymentIdParam, createDeploymentRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
