/*
 * ICOS Shell
 *
 * This is the ICOS Shell based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package shellbackend

type Resource struct {

	Id int64 `json:"id"`

	Name string `json:"name,omitempty"`

	Type string `json:"type"`

	ParentId int64 `json:"parentId,omitempty"`

	Status string `json:"status,omitempty"`
}

// AssertResourceRequired checks if the required fields are not zero-ed
func AssertResourceRequired(obj Resource) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"type": obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseResourceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Resource (e.g. [][]Resource), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResourceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResource, ok := obj.(Resource)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResourceRequired(aResource)
	})
}
