/*
 * ICOS Shell
 *
 * This is the ICOS Shell based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package shellbackend




type Deployment struct {

	// Unique identifier of the deployment
	Id int64 `json:"id"`

	// Name of the deployment
	Name string `json:"name,omitempty"`

	// Status of the deployment
	Status string `json:"status,omitempty"`
}

// AssertDeploymentRequired checks if the required fields are not zero-ed
func AssertDeploymentRequired(obj Deployment) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertDeploymentConstraints checks if the values respects the defined constraints
func AssertDeploymentConstraints(obj Deployment) error {
	return nil
}
