/*
 * ICOS Shell
 *
 * This is the ICOS Shell based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package shellbackend

type Deployment struct {

	Id int64 `json:"id"`

	Name string `json:"name,omitempty"`

	Status string `json:"status,omitempty"`
}

// AssertDeploymentRequired checks if the required fields are not zero-ed
func AssertDeploymentRequired(obj Deployment) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDeploymentRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Deployment (e.g. [][]Deployment), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDeploymentRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDeployment, ok := obj.(Deployment)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDeploymentRequired(aDeployment)
	})
}
