lighthouse: 
  controller_timeout: 60
  
keycloak: 
  server: https://keycloak.dev.icos.91.109.56.214.sslip.io
  client_id: shell-backend
  client_secret: ###
  realm: icos-dev
  username: admin
  password: ###

components: 
  job_manager: http://192.168.1.50:8082

