lighthouse: 
  controller_timeout: 60
  
keycloak: 
  server: https://keycloak.dev.icos.91.109.56.214.sslip.io
  client_id: shell-backend
  client_secret: rECpyPfRd4YaXtCcpJACFrfxQ1kcikG3
  realm: icos-dev

components: 
  job_manager: https://ocm-hub.bull1.ari-imet.eu
