/*
ICOS Shell

This is the ICOS Shell based on the OpenAPI 3.0 specification.

API version: 1.0.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shellclient

import (
	"encoding/json"
)

// checks if the CreateDeploymentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDeploymentRequest{}

// CreateDeploymentRequest struct for CreateDeploymentRequest
type CreateDeploymentRequest struct {
	Application string `json:"application"`
	Requirements []string `json:"requirements"`
}

// NewCreateDeploymentRequest instantiates a new CreateDeploymentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDeploymentRequest(application string, requirements []string) *CreateDeploymentRequest {
	this := CreateDeploymentRequest{}
	this.Application = application
	this.Requirements = requirements
	return &this
}

// NewCreateDeploymentRequestWithDefaults instantiates a new CreateDeploymentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDeploymentRequestWithDefaults() *CreateDeploymentRequest {
	this := CreateDeploymentRequest{}
	return &this
}

// GetApplication returns the Application field value
func (o *CreateDeploymentRequest) GetApplication() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Application
}

// GetApplicationOk returns a tuple with the Application field value
// and a boolean to check if the value has been set.
func (o *CreateDeploymentRequest) GetApplicationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Application, true
}

// SetApplication sets field value
func (o *CreateDeploymentRequest) SetApplication(v string) {
	o.Application = v
}

// GetRequirements returns the Requirements field value
func (o *CreateDeploymentRequest) GetRequirements() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Requirements
}

// GetRequirementsOk returns a tuple with the Requirements field value
// and a boolean to check if the value has been set.
func (o *CreateDeploymentRequest) GetRequirementsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Requirements, true
}

// SetRequirements sets field value
func (o *CreateDeploymentRequest) SetRequirements(v []string) {
	o.Requirements = v
}

func (o CreateDeploymentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDeploymentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["application"] = o.Application
	toSerialize["requirements"] = o.Requirements
	return toSerialize, nil
}

type NullableCreateDeploymentRequest struct {
	value *CreateDeploymentRequest
	isSet bool
}

func (v NullableCreateDeploymentRequest) Get() *CreateDeploymentRequest {
	return v.value
}

func (v *NullableCreateDeploymentRequest) Set(val *CreateDeploymentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeploymentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeploymentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeploymentRequest(val *CreateDeploymentRequest) *NullableCreateDeploymentRequest {
	return &NullableCreateDeploymentRequest{value: val, isSet: true}
}

func (v NullableCreateDeploymentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeploymentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


